SELECT * FROM CUSTOMERS
WHERE CUSTOMERNAME LIKE 'A%'

SELECT * FROM CUSTOMERS
WHERE BIRTHDATE BETWEEN '1990-01-01' AND '1995-12-31'

SELECT * FROM CUSTOMERS C
JOIN CITIES CT ON CT.ID=C.CITYID
WHERE CT.CITY='ÝSTANBUL'

SELECT *
FROM (SELECT *,
(SELECT CITY FROM CITIES CT
WHERE CT.ID=C.CITYID) CITY
FROM CUSTOMERS C) T
WHERE T.CITY='ÝSTANBUL'

SELECT CT.CITY,
(SELECT COUNT(*) FROM CUSTOMERS C
WHERE C.CITYID=CT.ID) MUSTERISAYISI
FROM CITIES CT

SELECT CT.CITY,COUNT(C.ID) MUSTERISAYISI FROM CITIES CT
JOIN CUSTOMERS C ON C.CITYID=CT.ID
GROUP BY CT.CITY
HAVING COUNT(C.ID) > 10
ORDER BY MUSTERISAYISI DESC

SELECT CT.CITY,C.GENDER,COUNT(*) MUSTERISAYISI FROM CUSTOMERS C
JOIN CITIES CT ON CT.ID=C.CITYID
GROUP BY CT.CITY,C.GENDER

ALTER TABLE CUSTOMERS
ADD AGEGROUP VARCHAR(50)

ALTER TABLE CUSTOMERS
DROP COLUMN AGEGROUP

UPDATE CUSTOMERS
SET AGEGROUP=
CASE 
	WHEN DATEDIFF(YEAR,BIRTHDATE,GETDATE()) BETWEEN 20 AND 35 THEN '20-35'
	WHEN DATEDIFF(YEAR,BIRTHDATE,GETDATE()) BETWEEN 36 AND 45 THEN '36-45'
	WHEN DATEDIFF(YEAR,BIRTHDATE,GETDATE()) BETWEEN 46 AND 55 THEN '46-55'
	WHEN DATEDIFF(YEAR,BIRTHDATE,GETDATE()) BETWEEN 55 AND 65 THEN '55-65'
	ELSE '65-'
END

SELECT C.*,D.DISTRICT FROM CUSTOMERS C
JOIN CITIES CT ON CT.ID=C.CITYID
JOIN DISTRICT D ON C.DISTRICTID=D.ID
WHERE D.DISTRICT<>'KADIKÖY' AND CT.CITY='ÝSTANBUL'


SELECT *,SUBSTRING(TELNR1,0,6) TELNR1OP,SUBSTRING(TELNR2,0,6) TELNR2OP 
FROM CUSTOMERS


SELECT DISTINCT TELNR1OP
FROM(SELECT SUBSTRING(TELNR1,0,6) TELNR1OP,SUBSTRING(TELNR2,0,6) TELNR2OP 
FROM CUSTOMERS
) T

SELECT TELNR1OP,TELNR2OP,COUNT(*) TELNROPERATORSAYISI
FROM
(
SELECT 
CASE
	WHEN C.TELNR1 LIKE '(50%' OR C.TELNR1 LIKE '(55%' THEN 'X'
	WHEN C.TELNR1 LIKE '(54%' THEN 'Y'
	ELSE 'Z'
END TELNR1OP,
CASE
	WHEN C.TELNR2 LIKE '(50%' OR C.TELNR2 LIKE '(55%' THEN 'X'
	WHEN C.TELNR2 LIKE '(54%' THEN 'Y'
	ELSE 'Z'
END TELNR2OP
FROM CUSTOMERS C
) T
GROUP BY TELNR1OP,TELNR2OP
ORDER BY 1

SELECT CT.CITY SEHIR,(SELECT TOP 1 DISTRICT FROM DISTRICT D
JOIN CUSTOMERS C ON D.ID=C.DISTRICTID
WHERE CT.ID=D.CITYID 
GROUP BY D.DISTRICT
ORDER BY COUNT(*) DESC) AS ILCE,
(SELECT TOP 1 COUNT(*) MUSTERISAYISI FROM DISTRICT D
JOIN CUSTOMERS C ON C.DISTRICTID=D.ID
WHERE D.CITYID=CT.ID
GROUP BY D.DISTRICT
ORDER BY MUSTERISAYISI DESC) MUSTERISAYISI
FROM CITIES CT
ORDER BY MUSTERISAYISI DESC

SELECT *,DATENAME(DW,BIRTHDATE) DOGUMGUNU FROM CUSTOMERS
ORDER BY BIRTHDATE DESC









