SELECT COUNT(DISTINCT MASTERID) FROM FLO
WHERE FIRST_ORDER_DATE IS NOT NULL


SELECT SUM(ORDER_NUM_TOTAL_EVER_OFFLINE+ORDER_NUM_TOTAL_EVER_ONLINE) TOPLAMALISVERISSAYISI,
SUM(CUSTOMER_VALUE_TOTAL_EVER_OFFLINE+CUSTOMER_VALUE_TOTAL_EVER_ONLINE) TOPLAMCIRO
FROM FLO

SELECT SUM(CUSTOMER_VALUE_TOTAL_EVER_OFFLINE+CUSTOMER_VALUE_TOTAL_EVER_ONLINE) 
/SUM(ORDER_NUM_TOTAL_EVER_OFFLINE+ORDER_NUM_TOTAL_EVER_ONLINE) ORTALAMACIRO
FROM FLO


SELECT LAST_ORDER_CHANNEL,
CASE
	WHEN LAST_ORDER_CHANNEL<>'Offline' THEN SUM(CUSTOMER_VALUE_TOTAL_EVER_ONLINE)
	ELSE SUM(CUSTOMER_VALUE_TOTAL_EVER_OFFLINE)
END TOPLAMCIRO,
CASE 
	WHEN LAST_ORDER_CHANNEL<>'Offline' THEN SUM(ORDER_NUM_TOTAL_EVER_ONLINE)
	ELSE SUM(ORDER_NUM_TOTAL_EVER_OFFLINE)
END TOPLAMALISVERISSAYISI
FROM FLO
GROUP BY LAST_ORDER_CHANNEL


SELECT STORE_TYPE,SUM(CUSTOMER_VALUE_TOTAL_EVER_OFFLINE+CUSTOMER_VALUE_TOTAL_EVER_ONLINE) FROM FLO
GROUP BY STORE_TYPE


SELECT DATEPART(YEAR,FIRST_ORDER_DATE) YIL,SUM(ORDER_NUM_TOTAL_EVER_OFFLINE+ORDER_NUM_TOTAL_EVER_ONLINE) TOPLAMALISVERISSAYISI
FROM FLO
GROUP BY DATEPART(YEAR,FIRST_ORDER_DATE)


SELECT LAST_ORDER_CHANNEL,
CASE
	WHEN LAST_ORDER_CHANNEL<>'Offline' THEN SUM(CUSTOMER_VALUE_TOTAL_EVER_ONLINE)/SUM(ORDER_NUM_TOTAL_EVER_ONLINE)
	ELSE SUM(CUSTOMER_VALUE_TOTAL_EVER_OFFLINE)/SUM(ORDER_NUM_TOTAL_EVER_OFFLINE)
END ORTALAMACIRO
FROM FLO
GROUP BY LAST_ORDER_CHANNEL


SELECT TOP 1 INTERESTED_IN_CATEGORIES_12,COUNT(*) KATEGORISAYISI FROM FLO
GROUP BY INTERESTED_IN_CATEGORIES_12
ORDER BY KATEGORISAYISI DESC


SELECT TOP 1 STORE_TYPE,COUNT(*) STORETYPESAYISI FROM FLO
GROUP BY STORE_TYPE
ORDER BY STORETYPESAYISI DESC



SELECT F.LAST_ORDER_CHANNEL,
(
SELECT TOP 1 INTERESTED_IN_CATEGORIES_12 FROM FLO
GROUP BY LAST_ORDER_CHANNEL,INTERESTED_IN_CATEGORIES_12
HAVING LAST_ORDER_CHANNEL=F.LAST_ORDER_CHANNEL
ORDER BY COUNT(*) DESC 
) ENCOKILGIGORENKATEGORI,
(
SELECT TOP 1
CASE 
WHEN F.LAST_ORDER_CHANNEL<>'Offline' THEN SUM(CUSTOMER_VALUE_TOTAL_EVER_ONLINE) 
ELSE SUM(CUSTOMER_VALUE_TOTAL_EVER_OFFLINE) 
END AS TOPLAMCIRO
FROM FLO
GROUP BY LAST_ORDER_CHANNEL,INTERESTED_IN_CATEGORIES_12
HAVING LAST_ORDER_CHANNEL=F.LAST_ORDER_CHANNEL
ORDER BY COUNT(*) DESC 
) TOPLAMCIRO
FROM FLO F
GROUP BY F.LAST_ORDER_CHANNEL


SELECT TOP 1 MASTERID,MAX(ORDER_NUM_TOTAL_EVER_OFFLINE+ORDER_NUM_TOTAL_EVER_ONLINE) TOPLAMALISVERISSAYISI FROM FLO
GROUP BY MASTERID
ORDER BY TOPLAMALISVERISSAYISI DESC


SELECT (CUSTOMER_VALUE_TOTAL_EVER_OFFLINE+CUSTOMER_VALUE_TOTAL_EVER_ONLINE)/(ORDER_NUM_TOTAL_EVER_OFFLINE+ORDER_NUM_TOTAL_EVER_ONLINE) ORTALAMACIRO,
(ORDER_NUM_TOTAL_EVER_OFFLINE+ORDER_NUM_TOTAL_EVER_ONLINE)/(DATEDIFF(DAY,FIRST_ORDER_DATE,LAST_ORDER_DATE)+1) ALISVERISSIKLIGIGUNDE
FROM FLO
WHERE MASTERID = (SELECT TOP 1 MASTERID FROM FLO
GROUP BY MASTERID
ORDER BY MAX(ORDER_NUM_TOTAL_EVER_OFFLINE+ORDER_NUM_TOTAL_EVER_ONLINE) DESC)


SELECT TOP 100 SUM(CUSTOMER_VALUE_TOTAL_EVER_OFFLINE+CUSTOMER_VALUE_TOTAL_EVER_ONLINE) TOPLAMCIRO,
MAX(ORDER_NUM_TOTAL_EVER_OFFLINE+ORDER_NUM_TOTAL_EVER_ONLINE)/(MAX(DATEDIFF(DAY,FIRST_ORDER_DATE,LAST_ORDER_DATE))+1) ALISVERISSIKLIGIGUNDE
FROM FLO
GROUP BY MASTERID
ORDER BY TOPLAMCIRO DESC


SELECT FLO.* FROM (SELECT TOP 1 FLO.MASTERID, 
CASE 
	WHEN FLO.LAST_ORDER_CHANNEL<>'Offline' THEN SUM(FLO.ORDER_NUM_TOTAL_EVER_ONLINE)
	ELSE SUM(FLO.ORDER_NUM_TOTAL_EVER_OFFLINE)
END AS ALISVERISSAYISI
FROM(SELECT TOP 1 LAST_ORDER_CHANNEL,
CASE 
	WHEN LAST_ORDER_CHANNEL<>'Offline' THEN SUM(ORDER_NUM_TOTAL_EVER_ONLINE)
	ELSE SUM